require 'rake'
require 'fileutils'


desc "Install vundle for vim plugins"
task :default do
  target = "~/.vim/vundle.git"
  git_clone('http://github.com/gmarik/vundle.git', target)
  puts "Running BundleInstall to install plugins...this will take a couple minutes."
  `vim +BundleInstall +qall`
  puts "vim plugins installed."
end

def git_clone(repo, target)
  path = translate_path(target)
  FileUtils.rm_rf(path) if File.exists?(path)
  `git clone ""#{repo}"" "#{target}"`
end

def self.translate_path(path)
  if path[0].chr === '~'
    path[0] = ENV['HOME']
  end
end

