#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
. script/homebrew

# move to script/rbenv
#rbenv install 1.9.3-p194
#rbenv global 1.9.3-p194
#rbenv rehash

rake install

cd ~/projects
git clone https://github.com/jkahne/tmux-MacOSX-pasteboard.git
cd tmux-MacOSX-pasteboard 
make reattach-to-user-namespace
mv reattach-to-user-namespace /usr/local/bin


#. osx/set-defaults.sh
