#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade


# Install grc and coreutils
#brew install grc coreutils

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
brew tap homebrew/dupes

# brew install chruby


#brew install ack
brew install tree
brew install webkit2png

brew install watch

#brew install libiconv 
brew install imagemagick 
brew install libpng 
brew install cmake 
# brew install ghostscript 
# brew install jasper 
brew install redis 
brew install ctags 
brew install the_silver_searcher
# brew install qt
# brew install libxml2
# brew install libxslt
# brew install libiconv
# brew link libiconv
# brew install tmux

brew cleanup


