#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew); then
  echo "Installing homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade


if [ ! "$(brew ls --versions coreutils)" ]; then
  echo "Installing coreutils"
  echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
  brew install coreutils
fi

if [ ! "$(brew ls --versions cmake)" ]; then
  echo "Installing cmake"
  brew install cmake
fi

if [ ! "$(brew ls --versions grc)" ]; then
  echo "Installing grc"
  brew install grc
fi

if [ ! "$(brew ls --versions editorconfig)" ]; then
  echo "Installing editorconfig"
  brew install editorconfig
fi

if [ ! "$(brew ls --versions gcc)" ]; then
  echo "Installing gcc"
  brew install gcc
fi

if [ ! "$(brew ls --versions gpg)" ]; then
  echo "Installing gpg"
  brew install gpg
fi

if [ ! "$(brew ls --versions neovim)" ]; then
  echo "Installing neovim"
  brew install neovim
fi

if [ ! "$(brew ls --versions autojump)" ]; then
  echo "Installing autojump"
  brew install autojump
fi

if [ ! "$(brew ls --versions overmind)" ]; then
  echo "Installing overmind"
  brew install overmind
fi

if [ ! "$(brew ls --versions openssl)" ]; then
  echo "Installing openssl"
  brew install openssl
fi

if [ ! "$(brew ls --versions bat)" ]; then
  echo "Installing bat"
  brew install bat
fi


if [ ! "$(brew ls --versions poppler)" ]; then
  echo "Installing poppler"
  brew install poppler
fi

if [ ! "$(brew ls --versions curl)" ]; then
  echo "Installing curl"
  brew install curl
fi

if [ ! "$(brew ls --versions diff-so-fancy)" ]; then
  echo "Installing diff-so-fancy"
  brew install diff-so-fancy
fi
if [ ! "$(brew ls --versions qt)" ]; then
  echo "Installing qt"
  brew install qt
fi
if [ ! "$(brew ls --versions ripgrep)" ]; then
  echo "Installing ripgrep"
  brew install ripgrep
fi
if [ ! "$(brew ls --versions fzf)" ]; then
  echo "Installing fzf"
  brew install fzf
fi
if [ ! "$(brew ls --versions tree)" ]; then
  echo "Installing tree"
  brew install tree
fi
if [ ! "$(brew ls --versions universal-ctags)" ]; then
  echo "Installing universal-ctags"
  brew install universal-ctags
fi
if [ ! "$(brew ls --versions gnu-tar)" ]; then
  echo "Installing gnu-tar"
  brew install gnu-tar
fi
if [ ! "$(brew ls --versions graphviz)" ]; then
  echo "Installing graphviz"
  brew install graphviz
fi
if [ ! "$(brew ls --versions wget)" ]; then
  echo "Installing wget"
  brew install wget
fi
if [ ! "$(brew ls --versions imagemagick)" ]; then
  echo "Installing imagemagick"
  brew install imagemagick
fi
if [ ! "$(brew ls --versions chromedriver)" ]; then
  echo "Installing chromedriver"
  brew install chromedriver
fi
if [ ! "$(brew ls --versions dbeaver-community)" ]; then
  echo "Installing dbeaver-community"
  brew install dbeaver-community
fi
if [ ! "$(brew ls --versions redis)" ]; then
  echo "Installing redis"
  brew install redis
fi





# Install GNU core utilities (those that come with OS X are outdated)
# brew install coreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
# brew install findutils



if [ ! "$(brew ls --versions watch)" ]; then
  echo "Installing watch"
  brew install watch
fi


brew cleanup
